name: Publish test CDN artifacts (versioned) to S3
run-name: Publish test CDN artifacts - versioned by @${{ github.actor }}

on:
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-cdn:
    if: |
      github.repository == 'IBM/plex'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: '0'
      - name: Use Node.js 20.x
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 #v4.0.4
        with:
          node-version: '20.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Build cdn folder
        run: yarn build:cdn
      - name: Upload to S3 bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.COMMON_COS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.COMMON_COS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.COMMON_COS_REGION }}
          AWS_S3_NAME: ${{ secrets.COMMON_COS_BUCKET }}
          AWS_S3_ENDPOINT: https://${{ secrets.COMMON_COS_ENDPOINT }}
          SOURCE_DIR: 'cdn'
          DEST_DIR_A: '/common/carbon/plex-test'
          DEST_DIR_B: '/common/carbon-for-ibm-dotcom/plex-test'
        run: |
          aws s3 cp ${{ env.SOURCE_DIR }} s3://${{ env.AWS_S3_NAME }}${{ env.DEST_DIR_A }} --endpoint-url ${{ env.AWS_S3_ENDPOINT }} --recursive --acl public-read --follow-symlinks &&  aws s3 cp ${{ env.SOURCE_DIR }} s3://${{ env.AWS_S3_NAME }}${{ env.DEST_DIR_B }} --endpoint-url ${{ env.AWS_S3_ENDPOINT }} --recursive --acl public-read --follow-symlinks
            