name: Publish test CDN artifacts (versioned) to S3
run-name: Publish test CDN artifacts - versioned by @${{ github.actor }}

on:
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-cdn:
    if: |
      github.repository == 'IBM/plex'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: '0'
      - name: Use Node.js 20.x
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 #v4.0.4
        with:
          node-version: '20.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Build cdn folder
        run: yarn build:cdn
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.COMMON_COS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.COMMON_COS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.COMMON_COS_REGION }}
      - name: Sync files to S3 bucket
        env: 
          SOURCE_DIR: 'cdn'
          DEST_DIR_A: '/common/carbon/plex-test'
          DEST_DIR_B: '/common/carbon-for-ibm-dotcom/plex-test'
          AWS_S3_NAME: ${{ secrets.COMMON_COS_BUCKET }}
        run: |
          aws s3 sync ${{ env.SOURCE_DIR }} s3://${{ env.AWS_S3_NAME }}${{ env.DEST_DIR_A }} && aws s3 sync ${{ env.SOURCE_DIR }} s3://${{ env.AWS_S3_NAME }}${{ env.DEST_DIR_B }}
            